/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javavisualizador.gui;

import java.io.FileInputStream; 
import java.io.IOException; 
import java.util.zip.ZipEntry; 
import java.util.zip.ZipInputStream; 
import javax.swing.DefaultListModel; 
import javax.swing.JOptionPane; 

public class CuadroPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public CuadroPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ArchivoJar = new javax.swing.JLabel();
        Boton1 = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        Info = new javax.swing.JLabel();
        Texto1 = new javax.swing.JTextField();
        Panel = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        BarraHerramienta = new javax.swing.JToolBar();
        BotonCarpeta = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        Fichero = new javax.swing.JMenu();
        Fichero1 = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        Ayuda1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javavisualizador/gui/folder.png")).getImage());

        ArchivoJar.setText("Archivo Jar");

        Boton1.setText("Ver Contenido");
        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        Panel1.setBackground(new java.awt.Color(102, 102, 102));
        Panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Info.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                InfoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Texto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto1ActionPerformed(evt);
            }
        });

        Lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Lista.setToolTipText("");
        Panel.setViewportView(Lista);

        BarraHerramienta.setFloatable(false);
        BarraHerramienta.setRollover(true);

        BotonCarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javavisualizador/gui/carpeta.png"))); // NOI18N
        BotonCarpeta.setFocusable(false);
        BotonCarpeta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonCarpeta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BotonCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCarpetaActionPerformed(evt);
            }
        });
        BarraHerramienta.add(BotonCarpeta);

        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Fichero.setText("Fichero");
        Fichero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Fichero1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Fichero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javavisualizador/gui/doc.png"))); // NOI18N
        Fichero1.setLabel("Item 1");
        Fichero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fichero1ActionPerformed(evt);
            }
        });
        Fichero.add(Fichero1);

        Menu.add(Fichero);

        Ayuda.setText("Ayuda");
        Ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Ayuda1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        Ayuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javavisualizador/gui/estrella.jpg"))); // NOI18N
        Ayuda1.setLabel("Ayuda1");
        Ayuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ayuda1ActionPerformed(evt);
            }
        });
        Ayuda.add(Ayuda1);

        Menu.add(Ayuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarraHerramienta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ArchivoJar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Texto1)
                        .addGap(18, 18, 18)
                        .addComponent(Boton1)
                        .addGap(128, 128, 128)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BarraHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArchivoJar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton1))
                .addGap(18, 18, 18)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
    
        Info.setText("Analizando ficheros JAR 1234"); 
        try { 
            DefaultListModel model = new DefaultListModel(); 
            ZipInputStream zip = new ZipInputStream(new FileInputStream(Texto1.getText())); 
            for (ZipEntry entry = zip.getNextEntry(); entry != null; entry = zip.getNextEntry()) { 
                model.addElement(entry.getName()); 
            } 
            Lista.setModel(model); 
            Info.setText("- Ficheros detectados : " + model.size()); 
        } catch (IOException ioe) { 
            Info.setText("- Archivos encontrados: 0"); 
                        JOptionPane.showMessageDialog(this,  ioe.getLocalizedMessage(),  "Ups!-  Se ha producido un error inesperado", 
JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Ayuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ayuda1ActionPerformed
        new Dialogo(this, true).setVisible(true);
    }//GEN-LAST:event_Ayuda1ActionPerformed

    private void Fichero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fichero1ActionPerformed
    dispose();
    }//GEN-LAST:event_Fichero1ActionPerformed

    private void Texto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto1ActionPerformed

    private void InfoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_InfoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoAncestorAdded

    private void BotonCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCarpetaActionPerformed
     Info.setText("Analizando ficheros JAR"); 
        try { 
            DefaultListModel model = new DefaultListModel(); 
            ZipInputStream zip = new ZipInputStream(new FileInputStream(Texto1.getText())); 
            for (ZipEntry entry = zip.getNextEntry(); entry != null; entry = zip.getNextEntry()) { 
                model.addElement(entry.getName()); 
            } 
            Lista.setModel(model); 
            Info.setText("- Ficheros detectados : " + model.size()); 
        } catch (IOException ioe) { 
            Info.setText("- Archivos encontrados: 0"); 
                        JOptionPane.showMessageDialog(this,  ioe.getLocalizedMessage(), " Error ", 
JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_BotonCarpetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuadroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuadroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuadroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuadroPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuadroPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArchivoJar;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuItem Ayuda1;
    private javax.swing.JToolBar BarraHerramienta;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton BotonCarpeta;
    private javax.swing.JMenu Fichero;
    private javax.swing.JMenuItem Fichero1;
    private javax.swing.JLabel Info;
    private javax.swing.JList<String> Lista;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JScrollPane Panel;
    private javax.swing.JPanel Panel1;
    private javax.swing.JTextField Texto1;
    // End of variables declaration//GEN-END:variables
}
